# Permalinks
permalink:           pretty
# relative_permalinks: true

# Setup
title:               정민이의 개발 아카이브
tagline:             "test"
description:         "test"
url:                 http://tape22.github.io
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              JungMin Hur
  url:               https://github.com/tape22
  email:             gjwjdlas@sookmyung.ac.kr

# Custom vars
version:             1.0.0

category_dir: category/
tag_dir: tag/